[project]
name = "MinServe"
version = "0.1.0"
description = "A minimalist gateway server on top of an AI/LLM Inference backend; for educational purposes"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.134.0",
    "uvicorn[standard]>=0.30.0",
]
